build:
  uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.3
  with:
    matrix: |
      include:
        - board: nice_nano_v2
          shield: charybdis_left
        - board: nice_nano_v2
          shield: charybdis_right
        - board: nice_nano_v2
          shield: settings_reset
